### ISSUE TITLE
Invoke execeptionCaught when exception occurs on the pipeline

### ISSUE THREAD

**Issue by zeroFruit** [zeroFruit/el#71]

**Comment by majecty** [comment]
I checked the el code to understand when we should call exceptionCaught.

I found that when calling a handler of an outbound event, `exceptionCaught` is not used. The AbstractContext code sets the error in the received promise.

When calling a handler of an inbound event, `exceptionCaught` is called when an error has occurred.

Since an explicit place starts the outbound event, the caller has to handle the exception. However, there is no caller in the inbound event like `channelActive`. So we need `exceptionCaught` handler to handle the errors.
